kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: allow-access-resourcequota-limitrange
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - limitranges
      - resourcequotas
