apiVersion: v1
kind: LimitRange
metadata:
  name: custom-limitrange
spec:
  limits:
    - default:
        cpu: 100m
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
        cpu: 50m
      max:
        cpu: 500m
        memory: 1.5Gi
      type: Container
