apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  inputs:
    - name: student-logs
      application:
        namespaces:
          - speaker01
          - student01
          - student02
          - student03
          - student04
          - student05
          - student06
          - student07
          - student08
          - student09
          - student10
          - student11
          - student12
          - student13
          - student14
          - student15
          - student16
          - student17
          - student18
          - student19
          - student20
          - student21
          - student22
          - student23
          - student24
          - student25
          - student26
          - student27
          - student28
          - student29
          - student30
  outputs:
    - name: fluentd-server
      type: fluentdForward
      url: 'tcp://fluentd.caj-common.svc:24224'
  pipelines:
    - detectMultilineErrors: true
      inputRefs:
        - infrastructure
        - application
        - audit
      name: all-to-default
      outputRefs:
        - default
    - name: forward-to-fluentd-server
      inputRefs:
        - student-logs
      outputRefs:
        - fluentd-server
