kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: allow-view-${STUDENT_ID}-pods
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
